### ISSUE TITLE
Guidance on Auth

### ISSUE THREAD

**Issue by ptimson** [AlpacaGoesCrazy/serverless-graphql-subscriptions#1]
Hey,

Thanks so much for your example, it's been great to understand how it should all work. The only thing I'm left confused by how to integrate Auth into the flow. I need to pass a token in at some point.

Currently the flow seems to be:
```
{ routeKey: "$connect" }

{ routeKey: "$default", body: {"type":"connection_init","payload":{}} }

{ routeKey: "$default", body: {"id":"1","type":"start","payload":{"variables":{},"extensions":{},"operationName":"listenMessage","query":"subscription listenMessage {\\n listenMessage\\n}\\n"}}}
```

It makes sense that the token is passed on the `$connect` and connection is rejected. I passed in the token with connectionParams

```
const wsOptions = {
  lazy: true,
  reconnect: true,
  connectionParams: async () => {
    const { token } = getToken()
    return { token }
  },
}

const subClient = new SubscriptionClient(WS_ENDPOINT, wsOptions, null, [])
const wsLink = new WebSocketLink(subClient)
```

But this only adds them into the second request (`connection_init`) and I'm not sure how to close the connection - I feel like it make most sense to pass them in the `$connect`.

**Comment by AlpacaGoesCrazy** [comment]
@ptimson 
The $connect route is handled outside of subscriptions-transport-ws protocol, so it would not be possible to get `connection_init` parameters there.
Alternatively you could use [AWS API Gateway authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-lambda-auth.html) to restrict connection access to your service.
The other way is you could provide HTTP header on establishing connection ([will not work with web browsers](https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api)), or Cookie.
The third way I am aware of is that you could save your authorization info from `connection_init` message to the connection state in DynamoDB and reject connections without proper authorization via `ApiGatewayManagementApi`'s [deleteConnection](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayManagementApi.html#deleteConnection-property)
