### ISSUE TITLE
... But what resolves the fields?

### ISSUE THREAD

**Issue by jdrydn** [AlpacaGoesCrazy/serverless-graphql-subscriptions#3]
Hi there,

First off, thanks for this, been using it to work out my own Serverless GraphQL implementation, and prefer this example to others due to the lack of abstraction - means I can really figure out how it all comes together!

What I don't seem to get is which part of this project resolves the fields for the GraphQL subscription?

Given the following schema:

```graphql
type Movie {
  id: ID! # IMDB ID
  title: String! # IMDB title
  icon: String! # Either 👍 or 👎 depending on rating
  rating: Float! # 
}

extend type Query {
  movie(id: ID!): Movie
  movies: [ Movie! ]
}

extend type Mutation {
  createMovie(title: String!, rating: Float!): Movie
}

extend type Subscription {
  latestMovie: Movie
}
```
```js
const resolvers = {
  Movie: {
    icon({ rating }) {
      return rating >= 7.0 ? '👍' : '👎';
    }
  },
  Mutation: {
    createMovie(root, { title, rating }) {
      const id = uuid();
      await publish('LATEST_MOVIE', { id, title, rating });
      return { id, title, rating };
    }
  },
  Subscription: {
    latestMovie: subscribe('LATEST_MOVIE')
  }
};
```

Now, I understand when I call `createMovie` the `icon` resolver is called passing the "created" entry thusly:

```graphql
mutation CreateNewMovie {
  createMovie(title: "Joker", rating: 8.5) {
    id
    title
    icon
    rating
  }
}
```

But at which point in this project is the `icon` resolver called for the following subscription?

```graphql
subscription GetLatestMovie {
  latestMovie {
    id
    title
    icon
    rating
  }
}
```

**Comment by AlpacaGoesCrazy** [comment]
@jdrydn Thank you for your question.
The thing is that I made this example only to show possibility of making graphql subscriptions work with apollo client with serverless architecture. This example is lacking most of the functionality of graphql subscriptions for example authorization, context handling, subscription resolvers, etc.

Regarding resolving subscription type's subfields:
Here in [publisher function](https://github.com/AlpacaGoesCrazy/serverless-graphql-subscriptions/blob/ce791665845bbc72afae2ea300515cc7c1272c17/server/src/models/Topic.js#L23) the correct approach would be to fetch an original query(and context which should be saved to server storage for each connection) for each connection and execute it against schema with published payload so all sub resolvers could be triggered.

Here you can see better implementation of [publisher function](https://github.com/michalkvasnicak/aws-lambda-graphql/blob/2dbcf723dd90db0df7141de52464ff645a9e9d67/packages/aws-lambda-graphql/src/DynamoDBEventProcessor.ts#L29) (in general [this library](https://github.com/michalkvasnicak/aws-lambda-graphql) is more sophisticated example of serverless subscriptions on AWS)
